version: '3'

services:
  smell-app:
    build:
      context: "./"
      dockerfile: "Dockerfile"
      args:
        - UID=1000
        - GID=1000
        - USERNAME=user
        - GROUPNAME=user
    ports:
      - 8083:8083
      - 5053:5053
    volumes:
      - ./:/src
    tty: true
